can_motors:
  - can_id: 1
    can_bus: 0
    name: "right_front_wheel_motor"
    type: "M3508"
  - can_id: 4
    can_bus: 0
    name: "left_front_wheel_motor"
    type: "M3508"
  - can_id: 3
    can_bus: 0
    name: "left_back_wheel_motor"
    type: "M3508"
  - can_id: 2
    can_bus: 0
    name: "right_back_wheel_motor"
    type: "M3508"
  - can_id: 5
    can_bus: 0
    name: "yaw_joint_motor"
    type: "GM6020"
  - can_id: 6
    can_bus: 0
    name: "trigger_joint_motor"
    type: "M3508"
    need_calibration: true
